---
analyzer:
  errors:
    flutter_style_todos: ignore
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
    public_member_api_docs: ignore
    sort_constructors_first: ignore
    use_setters_to_change_properties: ignore
  exclude:
    - build/**
    - lib/**.freezed.dart
    - lib/**.g.dart
  plugins:
    - custom_lint
include: package:very_good_analysis/analysis_options.yaml